# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Behnam Baharmand
tagline: "A Jekyll theme"
description: 'Assorted Thoughts Of a <a href="https://twitter.com/baharmand" target="_blank">Software Developer</a>.'
url: /
baseurl: https://behnum.github.io/blog.baharmand.com/

author:
  name: "Behnam Baharmand"
  url: https://twitter.com/baharmand

paginate: 5

# Custom vars
version: 1.1.0

github:
  repo: https://github.com/behnum/
