# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Behnam Baharmand
tagline: "A Jekyll theme"
description: 'Assorted Thoughts Of a <a href="https://github.com/behnum" target="_blank">Software Engineer</a>.'
url: https://behnum.github.io/blog.baharmand.com/
baseurl: https://behnum.github.io/blog.baharmand.com/

author:
  name: "Behnam Baharmand"
  url: https://twitter.com/baharmand

paginate: 5

# Custom vars
version: 1.1.0

github:
  repo: https://github.com/behnum/
