# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: Behnam Baharmand
tagline: "Assorted Thoughts Of a Software Engineer."
description: 'Assorted Thoughts Of a <a href="https://github.com/behnum" target="_blank">Software Engineer</a>.'
url: https://blog.baharmand.com
baseurl: ""

author:
  name: "Behnam Baharmand"
  url: https://twitter.com/baharmand

paginate: 5

# Custom vars
version: 1.1.1

github:
  repo: https://github.com/behnum/
